// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzCTQmcC1K_3Cvyu4Oi1kPMpm92RyniM8',
    appId: '1:89597174338:web:fc03f21656de813476c3db',
    messagingSenderId: '89597174338',
    projectId: 'o2-calculators',
    authDomain: 'o2-calculators.firebaseapp.com',
    storageBucket: 'o2-calculators.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPeg58JyDvFwcYGlHysIjPYpq5kq7lLy0',
    appId: '1:89597174338:android:bff3a7025888069376c3db',
    messagingSenderId: '89597174338',
    projectId: 'o2-calculators',
    storageBucket: 'o2-calculators.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmVdb630pvf-9_pDC5k2yes3PvQrL0PlM',
    appId: '1:89597174338:ios:df3a2955c87bdd6d76c3db',
    messagingSenderId: '89597174338',
    projectId: 'o2-calculators',
    storageBucket: 'o2-calculators.firebasestorage.app',
    iosBundleId: 'com.example.calculators',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmVdb630pvf-9_pDC5k2yes3PvQrL0PlM',
    appId: '1:89597174338:ios:df3a2955c87bdd6d76c3db',
    messagingSenderId: '89597174338',
    projectId: 'o2-calculators',
    storageBucket: 'o2-calculators.firebasestorage.app',
    iosBundleId: 'com.example.calculators',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzCTQmcC1K_3Cvyu4Oi1kPMpm92RyniM8',
    appId: '1:89597174338:web:e177c3c1f49d560576c3db',
    messagingSenderId: '89597174338',
    projectId: 'o2-calculators',
    authDomain: 'o2-calculators.firebaseapp.com',
    storageBucket: 'o2-calculators.firebasestorage.app',
  );
}
